### ISSUE TITLE
What are the best practices when contracting with clients on a 1099 basis?

### ISSUE THREAD

**Issue by eddiecervello** [coryhouse/ama#20]

**Comment by coryhouse** [comment]
Hi Eddie,

Honestly, I try to avoid contracts. I send an invoice requesting up front payment. Often the client doesn't bring it up. Why? Because many managers have the power to write checks, but not to sign contracts. So it's easier for them to pay than to sign.  Win win.

That said, it's probably smarter to have a standard contract that you present first. Honestly, I have a bit of a YOLO take on contracts. If someone doesn't like my work, then I'd refund their money. And I'm not going to take someone to court over lack of payment. Again, YOLO. I can make more money. And I read people's contract's myself and use my own brain. I don't use a lawyer for such things. So sometimes I pass on opportunities that require a long contract. In fact, just today I passed on a consulting gig because they wanted me to sign a 24 page contract. I didn't want to read 24 pages of legal, and told them I'd sign a simple NDA, but nothing more unless they committed to a minimum number of hours to justify my time. I'm lucky since I can afford to say no.

Not saying I'm smart, just being candid on my take, based on my values. There are smart people who disagree with me. Watch the [F you, pay me video on YouTube](https://www.youtube.com/watch?v=jVkLVRt6c1U) for a counterpoint to my views. I think they're myopically focused on assuring every payment occurs and too eager to go to court. YOLO. I'd rather focus my effort on being really good so people are comfortable paying me up front (and they nearly always do). Sure, there are other legal items in contracts, but most of those issues can be resolved with this: "I'm sorry. I messed up. Here's your money back." I keep my engagements small enough that I can do just that. Thankfully, I haven't had to refund anyone.

If you want a contract, you can check out clerky.com for some standard boilerplate. Dunno if they're good contracts though - a lawyer would have to vet 'em.
