### ISSUE TITLE
What do you think of Full Stack Web Application Development?

### ISSUE THREAD

**Issue by LIL626** [coryhouse/ama#22]
Hi Cory,

I am just going through your HTML5 Web Component Fundamentals course on Pluralsight... I am a complete beginner with some mandatory holidays, caused by the virus, so I decided to create a web application. I have written macros in excel before, and a few macros for a 3D design software both using VB, but that is about all my coding knowledge. I have watched about 45 hours of Pluralsight courses in 4 days, and I struggle to find the relevant things, as most beginner videos explain the basics too basic, but don't go into details on the genuinely new info. (I don't even need coding to understand what an if - else statement is - my mom shouted it at me enough as a child -, but what on earth is git? Sure I downloaded and installed it to follow the demos, now what, will it scan my entire computer and sell all my personal data???)  Yes I have very serious trust issues.

Your course was the first one that I actually started to find interesting, and the one that made most sense.

As I am drowning in resources - there are 95+hrs of Pluralsight courses on HTML CSS and JS (basics), purely on how to write these from scratch - a common element in these courses is: "Here is how you do it from scratch on your own, but don't do that, here is 5 alternatives for - libraries, frameworks etc. but you also have to learn these on top of what you just learned, they will introduce issues with dependencies, and you will struggle to switch between these. Good luck!!"

So 5th day into learning web application development I think I would like to go down the Full Stack route, assuming I understood that term right (Developing both Front and Rear end) and re-invent every wheel that rolls my way. <joke>Luckily as a Mechanical Design Engineer working in Motorsports, that's also what I do when I am not on holiday</joke>

After the essay, here are the questions:
- Whats your preferred method of deploying your web applications? 
- Why? 
- How are you certain that they are safe, both from hackers and from the third party you are/may be deploying it through? (I have trust issues with completely free resources that just say "promise we won't look" in a fancy formatted document)

The app I am developing (a demo for - as a first project) exists already and was created in the early 2000s and is unsupported now. It handles personal data, and while I will not input any real GDPR sensitive data into my demo app, I would like to begin development with the condition that it must be THAT secure. 

- What are 'Must have'-s even if I try to go about it the 'From Scratch' way?
- Do you have any more courses that go into detail on any of the topics I mentioned in my essay? (Security, frameworks and libraries, 'New Starter - kit' of 'Must Have'-s?
- If you personally don't, can you recommend certain courses to watch, read, work through?

Thank you!
Sorry for the long post! 
(Here is a Potato)

**Comment by coryhouse** [comment]
Hi - Congrats on getting started on a new career! I agree it can feel overwhelming. I suggest trying a lot of things at first, but pay attention to what catches your interest most. I suggest choosing a specialty after you've tried some things. This will help you get so good that people can't ignore you. It's hard to be remarkable if you're trying to learn everything. That's why I'm a front end specialist in just React. I can do many other things, but I am far more successful today as a focused specialist. I make more money because people pay me for being really good at something specific. 

For deploying web apps, I prefer to have a continuous integration (CI) server do it for me. Check out Netlify. They make it easy to deploy an app automatically. I'm a believer in automating anything that's redundant. If it's annoying and repetitive, make it easy and automatic. 

Regarding safety, I'm not certain anything is safe. But that's life. Nothing is certain. How are you certain your car is safe? Is that food you ordered safe? Life requires trusting other humans. Software is no different. That said, security is a big topic worth exploring and there are many things you can do to improve both your security, as well as your app's security. For now, just assume if it's popular, it's secure enough to be worth learning. :)

If you want to understand web app security, I found the book "Web Application Hacker's Handbook" useful many years ago. I don't have any specific courses to recommend.

For now, I wouldn't let security concerns stop you from coding. You can always pay a consultant a few hours to audit your work after you have something substantial to show. For now, just getting progress is valuable, and the lessons you learn along the way will make you better. Plus, even if you don't ship it, having code to show in interviews sets you apart. Few are willing to do such work in their free time. Credit to you!

Happy coding!
