### ISSUE TITLE
Career advice on how to get a dev job (preferably remote)

### ISSUE THREAD

**Issue by atilav** [coryhouse/ama#8]
Hi Cory,

Have a question and if you could give me an advice to follow that, and to somehow go to the right direction.

Have just basic knowledge of HTML and CSS, but don't know to write code for a site from scratch(for example). 

Want somehow to get into this world.

Would like to choose some path that could lead me to some job, not just job at some agency, but also to be able to work remotely! Is that possible?

Will you please, when you have time just for some short advice?

Thank you
A

**Comment by coryhouse** [comment]
Hi @atilav - I'd suggest starting by creating your own project from scratch. One great option is to create your own blog. The experience will expose you to real world challenges and the output will be something you can point to in interviews. If you're into gaming, you could try building an online game. Or, you could try building a simple clone of Twitter or StackOverflow.  

Point is:
1. Find something you're excited to build.
2. Use that as motivation to dig deep on the relevant topics. For the web, you'll want to know HTML, JavaScript and CSS. There are plenty of free resources online.
3. Start small. Get a simple static HTML page to display. Then figure out how to host it somewhere (I'd suggest Surge.sh or Netlify since they're free and easy). Then figure out how to add a second page. Then add navigation between the two pages. Then add styling to make it look nice. Then start adding more interactivity using forms and JavaScript.

Remote work is usually more practical for more experienced developers since it's handy having people nearby to help coach you when you're getting started, but it can also work remote if you have a strong team that's willing to help via online chat.

Have fun!
